name: Rust Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    container: ubuntu:devel
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        env:
          TZ: Europe/London
        run: |
          ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
          apt-get update
          apt-get install -y curl build-essential pkg-config libgtk-4-dev libadwaita-1-dev

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      
      - uses: actions/upload-artifact@v3
        with:
          name: mutiny
          path: target/debug/mutiny
